volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    # environment:
    #   POSTGRES_DB: ${DB_NAME}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${DB_NAME:-postgres}"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

  backend:
    build: ./backend
    # ports:
    #   - "9080:9080"
    env_file: .env
    # environment:
    #   DB_ENGINE: ${DB_ENGINE:-django.db.backends.postgresql}
    #   DB_HOST: db
    #   DB_PORT: 5432
    #   ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1,foodgram.myftp.biz}
    volumes:
      - static:/backend_static
      - media:/app/media
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:9080"
    depends_on:
      - db
      # db:
      #     condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9080/"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

  frontend:
    build: ./frontend
    command: cp -r /app/build/. /static/
    restart: "no"
    volumes:
      - static:/static

  gateway:
    build: ./gateway
    ports:
      - "9080:80"
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - backend
      - frontend
      # backend:
      #   condition: service_healthy
      # frontend:
      #   condition: service_completed_successfully
